// Generated by GraphWalker (http://www.graphwalker.org)
package com.mc646;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "com/mc646/exercicio11.json")
public interface BoundedQueueTestModelInterface {

    @Edge()
    void e_Enfileira();

    @Edge()
    void e_Reinicia();

    @Edge()
    void e_EnfileiraNaoCheio();

    @Vertex()
    void v_FilaVazia();

    @Edge()
    void e_criaBoundedQueue();

    @Edge()
    void e_Desenfileira();

    @Edge()
    void e_EnfileiraNulo();

    @Vertex()
    void v_ExecaoIlegalState();

    @Edge()
    void e_EnfileiraCheio();

    @Edge()
    void e_DesenfileiraNaoCheio();

    @Vertex()
    void v_Inicializa();

    @Vertex()
    void v_FilaCheia();

    @Vertex()
    void v_NullPointerException();

    @Vertex()
    void v_FilaNaoCheia();

    @Edge()
    void e_EnfileiraExcecao();

    @Edge()
    void e_DesenfileiraVazio();
}
